package com.lipsum.game.event;

public enum EventType {
    ENTITY_DEATH_EVENT,
    BUILDING_CREATION_EVENT,
    TILE_CLICKED_EVENT,
    TILE_DIRECTION_CHANGED_EVENT,
    SELECTED_BUILDING_TYPE_CHANGED_EVENT;
}
